### ISSUE TITLE
Modify article about `Static Site Generators (SSG)`

### ISSUE THREAD

**Issue by sentenz** [sentenz/convention#323]
# Static Site Generators (SSG)

- [1. Category](#1-category)
  - [1.2. Hugo](#12-hugo)
    - [1.2.1. Hoster](#121-hoster)
      - [1.2.1.1. GitLab](#1211-gitlab)
      - [1.2.1.2. GitHub](#1212-github)
- [2. Terminology](#2-terminology)
- [3. References](#3-references)

### 1.2. Hugo

Hugo is a static site generator that is renowned for its speed and flexibility. Hugo supports unlimited content types, taxonomies, menus, dynamic API-driven content without the need for plugins. It offers shortcodes for extended Markdown capabilities and comes with pre-made templates for SEO, commenting, or analytics. Hugo is multilingual and supports custom outputs like JSON or AMP.

##### 1.2.1.1. GitLab

1. Files and Folders

    - Project Layout
      > Directory structure of a Pages project. The `/docs` directory contains all markdown files that will be converted into HTML pages.

      ```markdown
      ├── /docs
      │   ├── /adr
      │   │   ├── merging-strategy-adr.md
      │   │   └── branching-strategy-adr.md
      │   ├── api.md
      │   └── README.md
      ```

    - `hugo.yaml`
      > The `hugo.yaml` file is the configuration file for Hugo. It defines the site configuration, and menu structure.

      ```yaml
      baseURL: "https://example.com/"
      languageCode: "en-us"
      title: "My New Hugo Site"
      theme: "ananke"
      publishDir: "public"

      menu:
        main:
          - identifier: "home"
            name: "Home"
            url: "/"
          - identifier: "adr"
            name: "ADR"
            url: "/adr/"
          - identifier: "api"
            name: "API"
            url: "/api/"
      ```

    - `./gitlab/pages.yml`
      > Configure GitLab CI by creating a `.gitlab/pages.yml` file to set up CI/CD pipeline for automatic deployment.
      >
      > NOTE GitLab Pages uses the `/public` directory to serve the static site. GitLab CI will automatically build and deploy the site to GitLab Pages.

      ```yaml
      ---
      spec:
        inputs:
          stage:
            default: pages
          job:
            default: pages
          image:
            default: alpine:latest
          tags:
            default: devops
          artifacts:
            default: "public"
          script:
            default: |
              doas apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community hugo
              hugo
      ---
      "$[[ inputs.job ]]":
        stage: $[[ inputs.stage ]]
        image: $[[ inputs.image ]]
        rules:
          - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        tags:
          - $[[ inputs.tags ]]
        script: $[[ inputs.script ]]
        artifacts:
          name: "$CI_JOB_NAME"
          paths:
            - $[[ inputs.artifacts ]]
      ```

    - `.gitlab-ci.yml`
      > Modify the GitLab CI file in the root of the `/project` directory to configure the CI/CD pipeline for automatic deployment.

      ```yaml
      ---
      include:
       - local: ".gitlab/pages.yml"
         inputs:
           stage: deploy
      ```

2. Command and Operations

    - Install
      > Install Hugo on the GitLab CI runner to build the Hugo site.

      ```bash
      doas apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community hugo
      ```

    - Setup
      > Initialize a new Hugo site in the current directory. This will create the necessary directory structure and configuration files for the Hugo site.

      ```bash
      hugo new site .
      ```

    - Build
      > Run the command to build the Hugo site. The output will be in the `/public` directory with the static site content.

      ```bash
      hugo
      ```

##### 1.2.1.2. GitHub

1. Files and Folders

    - Project Layout
      > Directory structure of a Pages project. The `/docs` directory contains all markdown files that will be converted into HTML pages.

      ```markdown
      ├── /docs
      │   ├── /adr
      │   │   ├── merging-strategy-adr.md
      │   │   └── branching-strategy-adr.md
      │   ├── api.md
      │   └── README.md
      ```

    - `hugo.yaml`
      > The `hugo.yaml` file is the configuration file for Hugo. It defines the site configuration, and menu structure.

      ```toml
      baseURL = "<https://example.com/>"
      languageCode = "en-us"
      title = "<Project>"
      publishDir = "public"

      [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
      [[menu.main]]
        identifier = "adr"
        name = "ADR"
        url = "/adr/"
      [[menu.main]]
        parent = "adr"
        name = "Merging Strategy"
        url = "/adr/merging-strategy-adr/"
      [[menu.main]]
        parent = "adr"
        name = "Branching Strategy"
        url = "/adr/branching-strategy-adr/"
      [[menu.main]]
        identifier = "api"
        name = "API"
        url = "/api/"
      ```

    - `.github/workflows/pages.yml`
      > Create a `.github/workflows/pages.yml` file to set up GitHub Actions for automatic deployment. Ensure that the `publish_dir` in the GitHub Actions workflow file points to the correct directory where the site is built.
      >
      > NOTE Enable GitHub Pages under the repository settings and select the `gh-pages` branch as the source. GitHub Actions will automatically build and deploy the site to the `gh-pages` branch.

      ```yaml
      name: Pages
      on:
        push:
          branches:
            - main
      permissions:
        contents: read
        pages: write
        id-token: write
      concurrency:
        group: "pages"
        cancel-in-progress: false
      defaults:
        run:
          shell: bash

      jobs:
        deploy:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v5
            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./public
            - name: Deploy Artifact
              id: deployment
              uses: actions/deploy-pages@v4
      ```

2. Command and Operations

    - Install
      > Install Hugo on the GitHub Actions to build the Hugo site.

      ```bash
      apt install hugo
      ```

    - Setup
      > Initialize a new Hugo site in the current directory. This will create the necessary directory structure and configuration files for the Hugo site.

      ```bash
      hugo new site .
      ```

    - Build
      > Run the command to build the Hugo site. The output will be in the `/public` directory with the static site content.

     ```bash
     hugo
     ```
